symbol_universe:
- AAPL
- ABBV
- AMD
- AMZN
- ARKK
- BA
- BAC
- BND
- CAT
- COP
- COST
- CRM
- CVX
- DE
- DIA
- DIS
- EEM
- EFA
- GE
- GOOG
- GOOGL
- HD
- HYG
- IBM
- IEF
- INTC
- IWM
- JNJ
- JPM
- KO
- LOW
- LQD
- MA
- META
- MRK
- MSFT
- NKE
- NVDA
- ORCL
- PEP
- PFE
- PG
- PYPL
- QQQ
- SHY
- SPY
- TGT
- TIP
- TLT
- TMO
- TSLA
- UNH
- V
- VNQ
- VTI
- WFC
- WMT
- XLE
- XLF
- XLK
- XLV
- XOM
risk_style: moderate
risk_constraints:
  max_drawdown_pct: 10
  min_holding_days: 3
  silent_after_loss_days: 5
